interface Type {
  [key: string]: string[];
}

export const regionsData: Type = {
  "CZ-JC": [
    "České Budějovice",
    "Český Krumlov",
    "Jindřichův Hradec",
    "Písek",
    "Prachatice",
    "Strakonice",
    "Tábor",
  ],
  "CZ-JM": [
    "Blansko",
    "Brno-město",
    "Brno-venkov",
    "Břeclav",
    "Hodonín",
    "Vyškov",
    "Znojmo",
  ],
  "CZ-KA": ["Cheb", "Karlovy", "Vary", "Sokolov"],
  "CZ-KR": [
    "Hradec Králové",
    "Jičín",
    "Náchod",
    "Rychnov nad Kněžnou",
    "Trutnov",
  ],
  "CZ-LI": ["Česká Lípa", "Jablonec nad Nisou", "Liberec", "Semily"],
  "CZ-MO": [
    "Bruntál",
    "Frýdek-Místek",
    "Karviná",
    "Nový",
    "Jičín",
    "Opava",
    "Ostrava-město",
  ],
  "CZ-OL": ["Jeseník", "Olomouc", "Prostějov", "Přerov", "Šumperk"],
  "CZ-PA": ["Chrudim", "Pardubice", "Svitavy", "Ústí nad Orlicí"],
  "CZ-ZL": ["Kroměříž", "Uherské Hradiště", "Vsetín", "Zlín"],
  "CZ-PL": [
    "Domažlice",
    "Klatovy",
    "Plzeň-jih",
    "Plzeň-město",
    "Plzeň-sever",
    "Rokycany",
    "Tachov",
  ],
  "CZ-PR": ["Praha"],
  "CZ-ST": [
    "Benešov",
    "Beroun",
    "Kladno",
    "Kolín",
    "Kutná Hora",
    "Mělník",
    "Mladá Boleslav",
    "Nymburk",
    "Praha-východ",
    "Praha-západ",
    "Příbram",
    "Rakovník",
  ],
  "CZ-US": [
    "Děčín",
    "Chomutov",
    "Litoměřice",
    "Louny",
    "Most",
    "Teplice",
    "Ústí nad Labem",
  ],
  "CZ-VY": [
    "Havlíčkův Brod",
    "Jihlava",
    "Pelhřimov",
    "Třebíč",
    "Žďár nad Sázavou",
  ],
};
